### ISSUE TITLE
GetTransaction: Card is missing "last_four" field from the JSON response

### ISSUE THREAD

**Issue by tonymitchell** [bambora-na/bambora-na-dotnet#20]
Calling GetTransaction in the Reporting API returns a Transaction object that contains a Card object. There is no LastFour field and the Number field is always empty.  The JSON response from the API contains the "last_four" field as part of the "card" object, but when you use the .NET classes do not contain this field.

**Comment by draganblagojevic** [comment]
'last_four', 'avs_result', 'cvd_result' and 'cavv_result' fields are added to Card object and are available in transaction response in the latest update to SDK. Note that SDK update brings breaking changes - it's rebranded as 'Bambora.NA.SDK' and namespaces changed. Other than namespaces there is no other breaking changes.
