### ISSUE TITLE
Package Beanstream 1.2.0 is not compatible with netcoreapp1.1

### ISSUE THREAD

**Issue by ajitscorpio** [bambora-na/bambora-na-dotnet#22]
I am working on a .NET core api and trying to setup Beanstream payment method. 

But getting this error:

Package Beanstream 1.2.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Beanstream 1.2.0 supports: net (.NETFramework,Version=v0.0)

What are my options now?

Thanks

**Comment by draganblagojevic** [comment]
Since version 2.x.x our SDK is available as  NuGet package for .NET standard 2.0 which you can use in .NET Core 2.0.
We don't have plans at the moment to support any previous version of .NET Core/.NET Standard
