### ISSUE TITLE
add .net core support 

### ISSUE THREAD

**Issue by avoxm** [bambora-na/bambora-na-dotnet#9]
The title says it all.

**Comment by ajitscorpio** [comment]
Any update on this one? @avoxm  were you able to use this package with core .net?

**Comment by draganblagojevic** [comment]
The latest update to SDK is available as .NET Standard 2.0 package as well.. Note that SDK update brings breaking changes - it's rebranded as 'Bambora.NA.SDK' and namespaces changed. Other than namespaces there is no other breaking changes.
